language: csharp
mono: none
dotnet: 3.0.0
script:
  - dotnet restore
  - dotnet build
notifications:
  email:
    recipients:
      - yo@edufdezsoy.es
    on_success: change # default: change
    on_failure: change # default: always

## Notes:
### Limit concurrent jobs to only 1
### Disable building PRs (might expose env vars)

## Environment Variables:

# TelegramBot_ApiToken                      test-bot-api-token
# TelegramBot_AllowedUserNames              main_tester,some_other_user
# TelegramBot_SuperGroupChatId              -1234
# TelegramBot_ChannelChatId                 -9876
# TelegramBot_PaymentProviderToken          token-from-stripe-test-bot
# TelegramBot_TesterPrivateChatId           1234
# TelegramBot_StickerOwnerUserId            1234
# TelegramBot_RegularMemberUserId           9876
# TelegramBot_RegularMemberUserName         main_tester
# TelegramBot_RegularMemberPrivateChatId    9876


